#.travis.yml
sudo: required

language: node_js
node_js:
  - "6.9"

services:
  - docker

branches:
  only:
    - develop
    - master

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --app mockup
  - ng build --prod --app prod
  - docker build -t devicemanagment/dm-frontend .

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  - docker push devicemanagment/dm-frontend
